### ISSUE TITLE
Accessibility: Color contrast on Touchpoints

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1045]
On Safari and Firefox, the touchpoints button has an default state (dark blue w/ dark grey type). I'm unsure if this meets color contrast minimums.

Default
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/435502b2-82ec-4561-b2af-6cb6df1441e0)

Hover
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/fc8aea59-3a98-4648-8474-9eaa72b04a80)

### Acceptance criteria (same as chrome)
- On all browsers, default state uses #0085ca with white type (matches experience on chrome)
- On all browsers, hover state uses #005ea2 with white type (matches experience on chrome)

Default
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/a53eeb07-8ee7-4068-bb4b-2cedeb23b86f)

Hover
![Image](https://github.com/weather-gov/weather.gov/assets/24654605/7408208a-df96-4cfa-8a43-f971801cbd64)

**Comment by colinmurphy01** [comment]
@partly-igor can you confirm the solution and hex codes in acceptance criteria?

**Comment by partly-igor** [comment]
I think the problem is may be the other way around. On Chrome you are seeing the "visited" version of the button-link with `#FFFFFF` on `#0085CA` , which is doesn't have enough contrast. The other states do have enough contrast (default and hover), and are what you see on Safari and Firefox. That said, the black on darker blue could be have more visual contrast even though it has enough calculated contrast. 

I think there are few changes to consider here:
1. Update the colors for default state of the button
2. Make the visited state of the button the same as the default state. 

For 1, we may want to consider a wider change since I think that is going to affect other default buttons on the site (we don't currently use many)

**Comment by partly-igor** [comment]
Completed in #1089
