### ISSUE TITLE
Safety Info - Fire

### ISSUE THREAD

**Issue by kmranjo** [weather-gov/weather.gov#1072]
Documented here: [link](https://docs.google.com/document/d/19-XmQYRI4GyzidxZMNuueHEEHwFeuzcWm1KLuZvQaxw/edit?usp=sharing)

Needs: 
- [x] Corey review
- [x] SME review

**Comment by kmranjo** [comment]
@coreypieper this one is ready for review

**Comment by coreypieper** [comment]
Reviewed and passed to fire weather SMEs (Katrina CCed).

**Comment by coreypieper** [comment]
Reviewed and approved by SME!

**Comment by kmranjo** [comment]
Final approved content for Red Flag Warning and Fire Weather Watch have been added to beta and published. 
Fire Weather Warning is not populating in the system as an option to select. 
@loganmcdonald-noaa @eric-gade @greg-does-weather  I think the list of event types is being populated from the API, right? So what does it mean if one of them doesn't appear there?

**Comment by greg-does-weather** [comment]
The event types are taxonomy terms that we manually entered. Since taxonomy terms are content, it should be totally fine to make any appropriate fixes directly in beta.

We have the taxonomy terms stored as a content export in our git repo, so once you've got everything nailed down, we should export those again so we can make sure our other environments are in sync.

**Comment by kmranjo** [comment]
Ah ok perfect. I updated the taxonomy in beta to include Fire Weather Warnings, and added that dynamic safety info. So now this one is all set.
