### ISSUE TITLE
Compliance with AC-02(4)

### ISSUE THREAD

**Issue by loganmcdonald-noaa** [weather-gov/weather.gov#1085]
### Description
We need to audit user account creation/deletion/update steps in the site in a persistent way. 

### Questions and Considerations
Consider a module like https://www.drupal.org/project/site_audit

### Acceptance Criteria
"Automatically audit account creation, modification, enabling, disabling, and removal actions"

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa we have a column for `Blocked - ISSO` and Compliance work that we couldn't move on without an ISSO, this is one ticket.

What should we do with these tickets and this column? I'd assume we'd manage compliance work the same way we manage all other work/tickets (inbox>priority columns>backlog>todo>doing>review>done). But if there's an alternative way, let me know.

**Comment by jamestranovich-noaa** [comment]
Let's chat about this during our compliance meeting tomorrow. Usually ISSOs are resistant to putting compliance progress tickets out in public (because there might be security implications) so we need to have a conversation first about how and where to track progress. For project management purposes, I think we can probably track compliance progress at a larger level, e.g., by control family but probably not by individual controls with any degree of specificity really. Added this discussion item to the agenda for tomorrow.

**Comment by colinmurphy01** [comment]
I'm here to support whatever you all think is right. Let me know how the discussion goes.

**Comment by jamestranovich-noaa** [comment]
Update from the meeting today: we can't use GitHub to track compliance progress. Instead, we'll track using some other mechanism: likely an internal NOAA google spreadsheet. So I'm closing these two issues for now. I opened another ticket to document what we end up using. https://github.com/weather-gov/weather.gov/issues/1662
