### ISSUE TITLE
Plan a round unmoderated of MVP feedback

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1123]
Design research plan for implementing one or more unmoderated research rounds over the next three months. 

This should include: 
- Defining any demographic constraints
- Determining what tool should be used for these and future unmoderated research
- Defining scenario/s and questions

cc @colinmurphy01

**Comment by sarahmhgov** [comment]
My thinking is that we may want to set ourselves up for more continuous unmoderated research in order to get comparative data over time. 

I'm hoping that we may be able to use userzoom in order to have a tool that NOAA already has access to. We can choose to recruit via userzoom (or usertesting) using our screener survey or recruit with our existing tools.

**Comment by sarahmhgov** [comment]
@colinmurphy01 for this sprint, what if I try to start a doc and have a proposal to discuss in a PO review? I can at least outline the actual testing goals and a medium term strategy for unmoderated, might be blocked a bit on what tool until we get more info on NOAAs access to userzoom to see if it's a good option.

**Comment by colinmurphy01** [comment]
That sounds great.

**Comment by sarahmhgov** [comment]
OK, I actually think I can start on this. I'll figure out an unmoderated protocol at least for a first round and go from this

**Comment by sarahmhgov** [comment]
In progress: https://docs.google.com/document/d/1CU3P9pYULl42zya4aOdyEbAHuRgivnCq0kHhpC2svhA/edit

**Comment by sarahmhgov** [comment]
Would love a working session on this if priority, I have a draft started

**Comment by colinmurphy01** [comment]
Adding to PO/Design Sync agenda this week
