### ISSUE TITLE
New Mexico SPS in API, not in beta

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1138]

**Comment by greg-does-weather** [comment]
We tracked this issue down, to some degree.

* This SPS was issued as a fire zone product, which is a policy violation:
  > For zone-based SPSs, Public Zones will be used, not Fire Weather Zones.
* The SPS was issued for fire weather zones:
  * NMZ110
  * NMZ111
  * NMZ112
  * NMZ113
* In the API, these were listed as the affected zones, but they were presented as public (forecast) zones rather than fire zones
* There are no public (forecast) zones for NMZ110, NMZ111, NMZ112, or NMZ113. Thus, no matter what location page you loaded, we would ***never*** match any alerts with those forecast zones.

I think it's now a product decision whether we want to chase this any further, but to a point Corey made in Slack, if we start trying to carve out special exceptions for every violation of policy directives, we're going to end up with a tangled mess of logic.
