### ISSUE TITLE
7-day tab skipping days 

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1151]
### Description

I was looking at a Texas forecast spot last night on my phone, and I noticed that it skipped days from May 2 (current day) to May 4.  I wanted to bring this up in case we were able to fix this.  I entered the location again a few minutes later and it showed the correct days (didn't skip).  I've seen this behavior a few times, but I've only noticed it over the past week.
![image](https://github.com/weather-gov/weather.gov/assets/139174561/726d87fc-da0e-4f90-9d08-fafc415b1e5d)

### Acceptance criteria

No days will be skipped when looking at a 7-day forecast.

- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
@shadkeene's screenshot about was for Dallas/Ft Worth at 10pm PST.

**Comment by coreypieper** [comment]
[North Platte, NE _ Weather.gov _ National Weather Service.pdf](https://github.com/weather-gov/weather.gov/files/15223803/North.Platte.NE._.Weather.gov._.National.Weather.Service.pdf)

New example.

Currently, severe/tor watches (which are unique, as they're issued by SPC vs. WFO's), have the impacted counties listed near the top, then a list of the cities, then a bulleted list of the counties (again). PDF example attached.

**Comment by coreypieper** [comment]
[active.txt](https://github.com/weather-gov/weather.gov/files/15224041/active.txt)
Here is the API alert endpoint for the case in my previous reply.

**Comment by greg-does-weather** [comment]
I *think* what we're seeing in this screenshot is that it should say "Today, May 3", and the time periods should be overnight, day, and night. So I don't think it's *skipping* anything, but I think it is mislabeling "today." At 10pm PT May 2, it would be midnight CT May 3.

I'm trying to replicate this issue right now without much success, but I've been able to create a lot of other weird issues that were totally my fault for not formatting dates and times correctly. 😛

**Comment by greg-does-weather** [comment]
Okay, I can now reproduce it. This will happen if two things are true:

1. the location's current time is after midnight
2. the first time period returned by the API's `/forecast` endpoint has a start time *before* midnight

When that happens, the labels for "today" and the first "night" period are incorrect. @shadkeene You got super lucky in stumbling across this case, because it should only happen for a few minutes a day. Generally, the first time period returned by the API's `/forecast` endpoint is the 0th minute of the current hour, but it can lag by a few minutes.

Anyway, now we know what's going on, and I'll get started on a fix!
