### ISSUE TITLE
Breaking down the time "walls" between tabs

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1406]
Right now there is no forecast information on the "current" tab, and feedback suggests people are looking for a summary of the forecast on that tab vs. the just the literal current data, like observations/satellite/etc.  Consider adding forecast information to the "current" tab or renaming current tab to "summary" or something else.

**Comment by colinmurphy01** [comment]
We've heard the problem before "people are looking for a summary of the forecast on that tab vs. the just the literal current data" but it's still a little unclear. It is likely a problem, but is it a tactical problem or a larger problem is a question.

With that there are a variety of solutions that could be explored some straight forward others a little more complex. Design will focus on exploring solutions, instead of designing a component ready for engineering. 

We will also be messing with navigation as we add pages and new components and so exploring alternative navigation structures that can be flexible with those changes is also something to consider.

**Comment by colinmurphy01** [comment]
We'll time-box this to 1 week, starting next week when research round has concluded and all designers can collab on it + POs back from OOO.

**Comment by partly-igor** [comment]
Reviewed with POs, and consensus being developed around the two tab direction. Will wait to implement until we start working on visualizations and figuring out how they affect and fit in to these designs.

**Comment by colinmurphy01** [comment]
Eng ticket placeholder: #1616

**Comment by colinmurphy01** [comment]
The new UX changes should address this. Will monitor.
