### ISSUE TITLE
Discuss WFO page components (ready for design vs. dev)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1414]
Goal: An inintial convo between design and eng on approach for WFO info, specific dynamic content.

**Comment by kmranjo** [comment]
Meeting notes from 7/9: 
We are aligned on the approach to have all information on the WFO page be dynamic (reusable) and the page itself be a template that authors cannot change. 
Next step will be a spike to determine how that set of information can be authored/stored/rendered. What is ideal public experience, ideal author experience. Will be creating a new ticket to cover that work. 

Once we have a solution, additional work will be needed to update the WFO Promo content type because it will be impacted.
