### ISSUE TITLE
Add wind cardinal direction and update icon

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#1445]
### Description
As described in #1400 we have heard feedback that users would like to see the cardinal directional for wind speed, in addition to an icon. This is also a good opportunity to update the wind icon to be more arrow-like again. 

[Figma documentation ](https://www.figma.com/design/w2QI2uTgaTWUPLHLi40mm1/Weather.gov-%E2%80%93-v0.2?node-id=9848-407691&t=AA0iHvSxZoZJTw8n-1)

[Updated wind icon](https://drive.google.com/file/d/1FS8EhclM-4pS--gyfrdrKXFAkhGs-Iol/view?usp=drive_link)

### Acceptance Criteria
- [ ] Text cardinal direction is added wherever we display wind speed (i.e. current conditions, hourly table)
- [ ] Wind direction icon is updated
- [ ] Spacing between the wind speed and wind direction text and icon matches the design

**Comment by greg-does-weather** [comment]
@partly-igor I don't know how to accomplish this:

>When rotating the icon, we should rotate the arrow vector itself rather than the viewbox. Rotating the vector keeps the space between the arrow and the text consistent. In contrast, rotating the viewbox creates additional space when the arrow is on a diagonal.

We currently rotate the `svg` element that links to the icon via a `use` tag:

```
<svg [...] style="transform: rotate(30deg);">
  <use xlink:href="[icon ID]"></use>
</svg>
```

It seems like the `svg` element is, essentially the viewbox in this scenario. The only way I can think of to rotate the image independently of the box that contains it would be to create a relatively positioned box, add the image with absolute positioning, and rotate the image from there.

I'm not entirely sure that would work either, though; I think CSS rotation transformations apply to the minimum bounding rectangle for the element. We even have to explicitly set the anchor/origin point for the rotation to be the center of the image container.

Continuing this sort of stream of consciousness comment... my gut is telling me that in order to preserve the spacing between the end of the text and the start of the icon, we'd not only need to rotate the image but also translate it some amount relative to the angle, which I think would be highly dependent on the icon, but not un-doable.
