### ISSUE TITLE
Decide on Project Management tool + clean up

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#168]
- [ ] Review proposal get feedback from Team
- [ ] Decide as team
- [ ] Clean up current github and test new kanban board

**Comment by colinmurphy01** [comment]
Still need feedback from team and status update on JIRA licenses from Kolly?

**Comment by shadkeene** [comment]
From Becky Cosgrove: _For the Jira question -- we do buy Jira licenses.  With your funding George.  Our FY23 purchase had an expansion of licenses to increase usage in NCO and also to move to their cloud-based product, so we could share some of those with the 18F team.  When we do the FY24 purchase, we can look again at usage and see if we need to increase the buy and therefore the funding.    As to the question of if it's a good idea for them to work there -- that really depends on the determination of who Tier 3 is.  If it's us, it surely does.  If it's not us, it's very likely those repositories would get migrated somewhere else.  So that's the risk being assumed here -- that it all might need to move once a Tier 3 is determined._

**Comment by shadkeene** [comment]
Shared latest information on licenses, in Slack msg.

**Comment by colinmurphy01** [comment]
Discussed as a team, we are comfortable with proposed plan for using Github Projects as a primary tool while long-term support is still TBD.

Revisit when long-term support is solidified.
