### ISSUE TITLE
AFD not formatting correctly after some headers or missing text

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1687]
Sometimes the first line of an AFD after certain headers are styled with a different font than the rest of the body of that section.

![image](https://github.com/user-attachments/assets/d41e9385-fbc0-492c-85e5-a2ee8e06a615)

![image](https://github.com/user-attachments/assets/674bc59d-6676-4052-931c-0aeafca2603a)

Additionally:
Albany's AFD Near Term Summary was cut off today. It should include
`.UPDATE...As of 630 AM EDT, patchy fog has developed within many`

![Image](https://github.com/user-attachments/assets/c875664f-f41a-4c5b-b664-c2d190dd18a5)

Acceptance criteria:
- [ ] There is consistent font in the bodies/paragraphs of each section of the AFD.

**Comment by colinmurphy01** [comment]
Need to confirm if this is a bug on our end, or a unique use case our parsing logic doesn't handle (and maybe shouldn't handle).

**Comment by colinmurphy01** [comment]
Also going to add Albany's use case to this ticket above.

**Comment by greg-does-weather** [comment]
[Albany AFD content from the API](https://github.com/user-attachments/files/16895997/aly-afd-bug.json)

**Comment by eric-gade** [comment]
I'm going to post my experiences looking into these issues here as I come across them. First up, the Albany example. The relevant source text looks like this:
```
.NEAR TERM /UNTIL 6 PM THIS EVENING/...
.UPDATE...As of 630 AM EDT, patchy fog has developed within many
river valleys across the region, some of which was locally
dense. This fog will dissipate between 8 and 10 AM.

Otherwise, forecast on track. Temps have dropped into the
lower/mid 40s across the southern Adirondacks, with mid 40s to
lower/mid 50s elsewhere.

[PREVIOUS 350 AM]...As of 345 AM EDT, skies remain clear 
outside of some patchy fog/low clouds forming immediately 
adjacent to some rivers/lakes. Temps have dropped into the 
lower/mid 40s across portions of the southern Adirondacks, with 
upper 40s to lower/mid 50s elsewhere.

Any patchy fog should dissipate between 8-10 AM. Otherwise, 
another sunny and warm day ahead, with afternoon high 
temperatures reaching 75-80 for most valley areas and 70-75 
across higher elevations.
```
To recap: headers are defined as starting on a newline beginning with `.` followed by a specific label in all caps, along with some optional subsequent text -- but only up to the following newline. That is my reading of [the directive](https://www.weather.gov/media/directives/010_pdfs/pd01005003curr.pdf).
  
In this case, the `.UPDATE` header directly underneath the `.NEAR TERM` header is _not_ properly formatted, since there is not a newline after the `630 AM EDT` portion of the text. So while we have a fix now that _does_ take care of the missing header and parsing out its content, it is going to render oddly:

![Screenshot 2024-09-18 at 3 20 03 PM](https://github.com/user-attachments/assets/31ae52a6-948c-45b3-8c65-c3deeb43e86e)
  
My preference is that we keep this odd rendering, because it demonstrates (again, to my reading) that ALY is not following the directive with this formatting
