### ISSUE TITLE
Fix icon for Iphone OS/home screens

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#1703]
We received feedback that when a user is saving beta.weather.gov on their Iphone, the NWS icon isn't showing.  I tested on Iphone SE and saved beta.weather.gov on the home screen via the Safari browser.  Here's what I see (see bottom two icons of beta.weather.gov on image):

![image](https://github.com/user-attachments/assets/945720ba-ffc6-4e12-819b-7e817fe3410c)

Acceptance criteria: 
- [ ] icon that displays on iphone home screens is same as other phone OSs

**Comment by jamestranovich-noaa** [comment]
Ah, you beat me to it! (I swear I searched the issues for this particular issue). 

I found this in New Relic. Original issue description:

### Description

In New Relic metrics and dashboards, we have quite the number of requests for an apple touch icon (`/apple-touch-icon.png`). 

It looks like some folks are using beta.weather.gov as a website link on the iOS home screen. This could be important because apple touch icons are part of being mobile/SEO friendly. 

Apple touch icons are automatically generated by favicon generators these days -- so we can probably re-use the current favicon images.

### Acceptance criteria

- [ ] We have `apple-touch-icon.png` (and its variants, such as `apple-touch-icon-precomposed.png`, `/apple-touch-icon-120x120.png` and `/apple-touch-icon-120x120-precomposed.png`)

**Comment by colinmurphy01** [comment]
As part of this we could deploy the app manifest capability to control this.

**Comment by jamestranovich-noaa** [comment]
We are getting more and more errors in New Relic about this issue. To be specific, we have gotten over 30 "apple touch icon missing" errors _today_ alone. Agree that we should tackle this soon -- it's an easy lift once we agree on which icon to use. 

![image](https://github.com/user-attachments/assets/24bd893d-3e0d-425b-838b-e743679ec7ec)

**Comment by colinmurphy01** [comment]
Thanks for the heads up on this. We'll reprioritize.

**Comment by colinmurphy01** [comment]
@greg-does-weather #1924 includes the NWS logo as the app icon for now right?

**Comment by greg-does-weather** [comment]
It's the NWS logo with a bright green background. Certainly not ideal! But icons cannot have transparent backgrounds, so I put in the green so we don't forget to make it something we actually want.

**Comment by colinmurphy01** [comment]
This will be fixed #1924
