### ISSUE TITLE
Update Weather Story component to reflect content/data from DSS Integration

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1739]
When we have an integration with DSS Builder and we haven't been able to train offices on content standards (which will take time), what should the weather story component look like if its receiving files and data from DSS Builder? 

Data we get from DSS Builder includes:
- Anywhere from 1 to 7+ images (typically displayed via tabs in the current site, [example from nashville](https://www.weather.gov/ohx/))
- An order of the images
- Title
- Description

Considerations:
- Do we want to support multiple images or not?
- If so, how do we want to display/navigate between them? 

Example of 7 tabs
![Image](https://github.com/user-attachments/assets/21adddd8-122a-4530-962e-489a54e66e63)

**Comment by jamestranovich-noaa** [comment]
Unfortunately, we have had to configure Drupal to store one `WFO Weather Story Upload` content type for each weather story image. This is because we do not know, _a priori_, how many images we will get from DSS builder. So images might continue to be WFO centric. Restated, all images will be bundled under that WFO. Which is basically due to how DSS builder works. For instance, https://www.weather.gov/source/hnx/WxStory/WeatherStory.xml (as of the time of this writing) gives us four images:

- https://www.weather.gov/images/hnx/WxStory/WeatherStory1.png
- https://www.weather.gov/images/hnx/WxStory/WeatherStory2.png
- https://www.weather.gov/images/hnx/WxStory/WeatherStory3.png
- https://www.weather.gov/images/hnx/WxStory/WeatherStory4.png 

Speaking of which, there's also some trickiness here because if DSS builder uploads 9 images one day for one WFO, and then the next day only 4 for that same WFO, we have to clear out the older images, as well. 

I guess what I'm saying here is that we kind of have to work around the limitations of DSS builder and how it thinks the data should be structured.

**Comment by colinmurphy01** [comment]
@jamestranovich-noaa what if we capped the amount of images we're uploading from DSS Builder? Would that make things simpler.

I think @kmranjo is thinking about that already.

**Comment by jamestranovich-noaa** [comment]
Capping the number of images might help! I want to leverage Drupal functionality (such as content types and JSON:API) as far as we can, but I don't think we should be strict about it. We can figure out alternate solutions if we want something more flexible or custom. What we have right now should work for experimentation and iteration, at least.

**Comment by colinmurphy01** [comment]
Was this picked up last sprint?

**Comment by partly-igor** [comment]
We got started on it – @kmranjo has pulled together a bunch of examples so we have a sense of the types and variety in the weather stories. I have not spent time working on the design yet however.

**Comment by colinmurphy01** [comment]
Roger. This is a priority for design/eng by end of week. So let's chat feasibility in planning today.

**Comment by partly-igor** [comment]
Updated #1793 with documentation

**Comment by colinmurphy01** [comment]
I believe this is `done` now since #1793 has been picked up.
