### ISSUE TITLE
e1.v2 static content (TBD)

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#183]
### Purpose
This should describe the purpose of the website in order to earn trust and qualify it's authority in weather. 

### Next steps

- [x] #280
  - [ ] Draft copy
- [x] #173 
  - [ ]  Apply styling rules

### Supported user stories
- 

### Story details: As a member of the public 
- 

### Design (define/discovery)
- 

### Support needed
- 

### Acceptance criteria
[will be added with design]

----
### Needed next action: design & define

```[tasklist]
### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [ ] Eng - feasibility and right-size
- [ ] UX - what and how to test
```

```[tasklist]
### Story details
-  [ ] Reviewed designs (must be attached)
-  [ ] Acceptance criteria define (added to this story)
```

**Comment by colinmurphy01** [comment]
@kmranjo when you get a chance can you document the component based on our proposal, so that we can pick it up when we have bandwidth?

**Comment by kmranjo** [comment]
@colinmurphy01 I'm actually a little unclear on this one just because of how it's framed. I think it's meant to be a component that allows static text to be authored on a page, and in the context of the trust/authority epic would be used to include something like the NWS mission on the homepage. Is that correct?

**Comment by kmranjo** [comment]
@colinmurphy01 Maybe we could discuss? I think I'm a little lost. I'm not sure this is connected to the WFO attribution (I am assuming that would not be able to be static content, since it has to populate based on location). And the additional site content ticket is about entire pages linked to in the footer. I'm looking into that one right now and it seems that for the most part we'll be starting out by linking to existing pages, and we can build out new ones later on if/when the content is updated. Those pages would need a text editor, but I wouldn't think we would want to make a different version based on styles only, would we? We could just make one and allow for different styles to be selected?
