### ISSUE TITLE
Question on Archive data from webservice API - WFO forecast office - Gridpoint forecast data

### ISSUE THREAD

**Issue by clarklight** [weather-gov/weather.gov#1859]
Hi, i had spent past week or 2 trying to find the Archive of the forecast data from the webservice API under 

[/gridpoints/{wfo}/{x},{y}](https://www.weather.gov/documentation/services-web-api#/default/gridpoint)
and [/gridpoints/{wfo}/{x},{y}/forecast](https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast)

Looking especially for the thunderstorm Probability and Lightning activity. 

Are they kept somewhere? If so, can anyone point me to it? 
Thank you
Thanks for your time
Clark

**Comment by jamestranovich-noaa** [comment]
Hello! These endpoints are for current forecasts. I believe there is no archived data, unfortunately. 

So it might be hard to capture these values -- `probabilityOfThunder` and `lightningActivityLevel` -- since you have to get the data as it happens or is forecast to happen for a specific location. You might be able to query active weather alerts for "severe thunderstorm warning" and the like (related [documentation](https://www.weather.gov/documentation/services-web-api#/default/alerts_active)) and then grab the corresponding location data, though. 

Does that help?

**Comment by colinmurphy01** [comment]
NCEI hosts archived observational data https://www.ncei.noaa.gov/products

However they have been significantly impacted by Helene and many of their services are currently down.
