### ISSUE TITLE
Chart tooltip: styling

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1882]
Current desktop
![Image](https://github.com/user-attachments/assets/c0963950-4d1f-47ba-9175-be2ae090ccb9)

Current mobile
![Image](https://github.com/user-attachments/assets/14316869-baa4-48b0-81be-bfa2b4fcddc8)

Considerations:
- Improve the stroke around the color for better visibility

Related:

**Comment by colinmurphy01** [comment]
Adding in the feedback from touchpoints here

> Now that the graphs are scrollable, and effortlessly readable, I would get rid of the mouse over info. On a mobile phone it tends to be annoying and distracting, at least for me it is. On a laptop or PC the graphs are so big, you Really don‚Äôt need Mouse over info.

**Comment by partly-igor** [comment]
Discussed in Slack on 10/24/24 – based on the feedback in touchpoints  and the fact that we are including a datalabel for every point, instead of restyling the tooltip we will remove it from all the charts for now. If this becomes an issue we can use the update styles created as part of this ticket.

**Comment by partly-igor** [comment]
I don't think we need a separate ticket, I can do it as part of this one.
