### ISSUE TITLE
Remove time zone labels in alert banners (indicating it's based on local time zone)

### ISSUE THREAD

**Issue by coreypieper** [weather-gov/weather.gov#1899]
Some alerts have timezones (e.g. "EDT") listed while other don't, despite all being EDT in this example. Our preference is to hide any reference of timezone in the banner.

![Screenshot 2024-10-09 at 6 11 15 PM](https://github.com/user-attachments/assets/9919c721-f39d-4f15-a6f6-e35c112120f5)

**Comment by colinmurphy01** [comment]
@kmranjo thoughts on this?

**Comment by kmranjo** [comment]
I'm inclined to think we actually don't need the timezone because the default thought here is going to be "of course its the local time zone". And having something like "9:00pm Thursday" is much easier to read than the full string. 
The time zone is also in the full alert text, so I think we could stick with our approach of simplifying the banners as much as possible and allowing the detail to appear in the full set of info.

**Comment by colinmurphy01** [comment]
@coreypieper let us know how you feel about that solution. If you agree, please update the description.

**Comment by greg-does-weather** [comment]
This seems correct. The question of what timezone are you looking at is only relevant where the user is not in the same timezone of the point they're looking at. That's the only way there's any ambiguity, and if we accept a little ambiguity for non-local users in exchange for speed of comprehension for affected users, that definitely seems right.
