### ISSUE TITLE
Missing WFO offices

### ISSUE THREAD

**Issue by jamestranovich-noaa** [weather-gov/weather.gov#1947]
### Description

When doing weather story image testing, I ran across `NWS Forecast Office Pocatello, ID` which maps to `PIH` but we don't have that entry in our taxonomy. It would be nice to have a comprehensive list (somehow) -- maybe from their org chart? CC @kmranjo since you may know more)

### Acceptance criteria

- [ ] Add test that checks for all of the known WFOs (Greg suggests: _before_ we add the missing WFOs)
- [ ] Changes have been tested for accessibility

**Comment by kmranjo** [comment]
Hmm.....I really thought we had all of them. I remember we had issues with some of them a while back because they had split names (like baltimore/washington) but you're right, I don't even see this one in the taxonomy. It sounds like you want me to hold off on adding it for now, right? 
I just counted through them and we have 120 WFO entries. I think the actual total is 122 so we are missing 2 of them. If Pocatello is one, I'm pretty sure Pago Pago is the other because right now we only list Honolulu and Guam under the Pacific region. Let me know when its ok to add them and I can do that.

**Comment by colinmurphy01** [comment]
@kmranjo would that be the reason why we're not getting the AFD either? #1927

**Comment by kmranjo** [comment]
I know less about how that is set up on the back end, but it's certainly possible.

**Comment by jamestranovich-noaa** [comment]
Oh, I didn't realize there were 120-odd WFOs. Do we have a list somewhere? It might be easier to update automatically -- I ran across this example by mere happenstance and (perhaps incorrectly) assumed we had more than a few WFOs missing.

**Comment by kmranjo** [comment]
The best source I've found is in the links on the accordions on this page: 
https://www.weather.gov/organization_prv/ 

It was definitely the "official" list at one time. However, it's definitely an old page and hasn't been updated in years, so some of the links don't work directly. For instance, the hawaii one looks broken. But if you search for Honolulu on the site and then look at what WFO it says is connected to that point forecast, you can reverse engineer it.

**Comment by colinmurphy01** [comment]
@coreypieper do you think the page is an official list of offices we can use? Is there another source that's regularly maintained?

**Comment by colinmurphy01** [comment]
This has been fixed by @greg-does-weather in #1927
