### ISSUE TITLE
[Feedback] Hawaii location name issue

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#1978]
When I entered my zip code (96789), it brings up Waipio Acres. That's wrong. It's Mililani. The old website gets this correct. It also brings up Honolulu International Airport as the observation station. That's wrong. It's Wheeler Airfield. The old website gets this correct.

**Comment by colinmurphy01** [comment]
This has come up a few times, is it time to go back to remembering the searched location name and just use that?

**Comment by greg-does-weather** [comment]
They typed in a ZIP code, not a location name, though.

**Comment by greg-does-weather** [comment]
We do have Mililani Town. https://beta.weather.gov/point/21.45/-158.012?.  But they both have the same ZIP code, and as we've discussed, a ZIP code is not a "point." It's not really even a polygon, though that's a reasonable mental model. So when you search for a ZIP code, ArcGIS gives us back some point that is somewhere inside that polygon. It happens to be the case that it gives us a point closer to Waipio Acres than to Miliani. We can't really do much about that.

If we had places as polygons instead of points, that'd be a huge help, but it appears that database doesn't exist anywhere we can get to.

**Comment by colinmurphy01** [comment]
Very good points, I didn't recognize that initially. Thank you.
