### ISSUE TITLE
Adopt a testing framework and begin writing tests

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#218]
Acceptance Criteria

- [ ] Look into cypress for end-to-end testing
- [ ] phpunit for unit testing
- [ ] ADR ( #201) is updated
- [ ] Running automated on a push (#232)

**Comment by colinmurphy01** [comment]
Considerations from refinement

- Look into cypress for end-to-end testing
- phpunit for unit testing

**Comment by greg-does-weather** [comment]
Current status:
- We have Cypress for e2e testing
- We have phpunit for PHP tests
- We are checking and enforcing minimum code coverage on PHP
  - Unclear if we should be unit testing Javascript or rely on e2e testing. Currently we have exactly one Javascript function and it's fully tested in e2e tests, but the practical upshot is that we can't capture coverage data that way. I think I'd rather not put in a bunch of Javascript-specific testing at this point because I'm not sure we're going to have very much.
- We still need to integrate a11y testing
