### ISSUE TITLE
Replace static css and js link tags with Drupal placeholder_token

### ISSUE THREAD

**Issue by claire-skies-noaa** [weather-gov/weather.gov#234]

**Comment by colinmurphy01** [comment]
@greg-does-weather putting this on your radar. Is this something we should do sooner rather than later?

**Comment by greg-does-weather** [comment]
To be honest, it's been sitting in the backlog because I'm not sure what it is and I haven't seen any issues or problems that made this ticket resonate with me. I'm sure it's here for a good reason, though, and I'd guess it's a small lift once we know what it means. So I think we should commit 30-60 minutes on research to understand what the ticket is for, and then just... do it. Unless it turns out to be a whole big thing; then we'll re-evaluate.
