### ISSUE TITLE
Avoid FOUT loading web fonts and USWDS

### ISSUE THREAD

**Issue by claire-skies-noaa** [weather-gov/weather.gov#260]
Preconnect from CDN rather than loading source code:

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:opsz,wght@6..12,500&display=swap" rel="stylesheet">
```

Also defer USWDS so it doesn't initialize a page layout.

Acceptance criteria

- [ ] Page loads "Nunito Sans" font without a delay. 
- [ ] Fallback font "sans-serif" does not appear.
- [ ] Page does not flash unstyled
- [ ] Page layout is not forced before content finishes loading (see browser dev console output for this one)

**Comment by greg-does-weather** [comment]
Oops. I co-opted this issue for another FOUC bug, but now I'm not sure this one is relevant anymore. I think Claire moved the fonts into our theme, so we're not getting them from Google anymore. There's still a flash where the font changes, though, so I'm going to investigate a little. Perhaps the `preconnect` just need to be changed.

**Comment by greg-does-weather** [comment]
Okay, this is still relevant. I had no idea FOUT was such a weird problem. Anyway...

For our HTTP/2 users, the FOUT should be pretty minimal because the fonts should come down nearly at the same time as the content since it's coming from the same host. For everyone else... I don't know.

At some point, we might need to sit down and tweak Apache settings to get public and browser caches to be our friends, or put something like Varnish in front of Apache.
