### ISSUE TITLE
Spike: Embeddable maps and radar

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#299]
### Background
Conduct a technical spike into radar products and if we can use them "out of the box".

### Supported user stories
- I want to understand when and where weather is developing according to my location (example developing precipitation in my area)

### Questions to answer
- Can they be embedded 
  - eventually by forecaster
- Can the view/layers can be preset, including
  - location
  - product type (Radar, Smoke, FIM)
- Can we tell it to render a user's location
- Can a user zoom in and out or navigate map
- Can the map be static and/or animated with time lapse 

### Considerations for spike
- [radar.weather.gov](http://radar.weather.gov/)
- [viewer.weather.noaa.gov](https://viewer.weather.noaa.gov/)
- Feedback from users that the current products are too slow to load, radar is pixelated, doesn't have necessarily details baked into the map (buildings)

**Comment by colinmurphy01** [comment]
@greg-does-weather can you update this to reflect progress and discussion links from slack?

**Comment by mgwalker** [comment]
Current status:

Implemented a super basic map with Leaflet, using OpenStreetMaps as a base layer and NCEP WMS services for base reflectivity radar. This basic map pulls in all of the available radar scans and animates over them. It doesn't provide any playback controls. We'll have a product discussion/decision about playback controls because maybe we don't want them on this page? We also need to pause and think about the mobile experience before going much further. E.g., for mobile users, maybe we don't want to immediately load the radar so we don't use up a lot of extra data, etc.

We have a meeting scheduled with Jonathan for 6 Dec to talk about radar.weather.gov and how we might be able to embed or borrow from that instead of reinventing a whole thing.

More history/context in [this Slack thread](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1701730036593769).

**Comment by colinmurphy01** [comment]
Doc for recording what we've found: https://docs.google.com/document/d/1dI-ux5X5YnOuwKgPgoSUSfWiNo5pCYuYFwE2OCczmHU/edit#heading=h.iueu58ttr7rl

**Comment by greg-does-weather** [comment]
:shrugging-person-made-of-symbols:

I think based on what I know our radar needs to be right now, we're in good shape. That may change once we get into research and design for radar needs, though.

**Comment by greg-does-weather** [comment]
Just a further update for future reference:

The maps Jonathan showed us were very similar to the ones I'd put together. He's using the same WMS services and everything. Where his really departs is he's done work on the map animation controls and, the thing I thought was super cool, he's done some optimizations around how he requests the layer tiles to reduce network traffic. I think if we continue with a tile-based WMS approach (which just feels right in my bones), we should definitely get back in touch with Jonathan to adopt his code.

**Comment by colinmurphy01** [comment]
With that summary I think can we call this spike `done`considering?

- [ ] We know what's easily available to us to support our core use cases
- [ ] We have an understanding of feasibility and LOE when we start designing a solution
- [ ] We have a primary candidate to use when we begin building

**Comment by greg-does-weather** [comment]
I think so. I feel like we have a better understanding of the dev/implementation side of things, and hopefully the experiments help clarify the product parts, too.
