### ISSUE TITLE
Add linter and formatter for HTML and Twig templates

### ISSUE THREAD

**Issue by mgwalker** [weather-gov/weather.gov#355]
### Description

Our automated code quality tools do not lint or format our HTML or Twig templates. We should pick tools, integrate them into our dev environment, and put them in our CI/CD pipeline.

There is a prettier [plugin](https://github.com/trivago/prettier-plugin-twig-melody) for Twig templates we may be able to use.

First identified #332

### Acceptance criteria

- [ ] We have added a linter/formatter in our dev environment
- [ ] We have added the same tools to our CI/CD pipeline
- [ ] We have updated our developer documentation accordingly

**Comment by greg-does-weather** [comment]
The prettier plugin is long abandoned. We can't use that one.

In fact, the landscape for Twig formatters and linters is barren. All of the options – *all of them* – are ancient, with one exception that runs in Python. I'm pretty strongly opposed to introducing any new languages or runtimes to our stack, and even if I wasn't, I don't like the way that tool formats the Twig – it actually makes it harder to read by squishing things into as few lines of code as possible.

Since we cannot satisfy the requirements of this ticket, I'm just gonna close it. We will continue to hold each other accountable for formatting in manual code reviews, but there just aren't any suitable automated tools for the job.
