### ISSUE TITLE
Log API errors

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#489]
We have observed the API failing. We'd like to get a sense of the frequency of it failing.

**Comment by colinmurphy01** [comment]
@shadkeene is going to regroup with NCO on this and raise issue to our champions.

**Comment by greg-does-weather** [comment]
I've added some basic logging for API server errors #511, but after talking to Kolly and Brian today, I'm not sure we need the logging since the problem is already known and tracked. Maybe we should still log the cases where after retrying a few times we still fail because those cases should be unusual?

**Comment by colinmurphy01** [comment]
Added the rest of the NCO team to the API sync. 

Next step for us was to regroup with them next week on the details within these questions.
