### ISSUE TITLE
Hazard - In effect from - until

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#749]
### Description

For an active hazard, if the the hazard is within the active time it should not include the "from Sunday..." 

![Image](https://github.com/weather-gov/weather.gov/assets/24654605/8de92f45-993a-4b35-a92d-85b9c56a876e)

[Example](https://beta.weather.gov/local/LOX/119/62#alert_2) from Ventura, CA on Monday at 3:30pm EST.

This one should read "In effect until Tuesday, 02/06..." within in the hazard and in the banner above.

### Acceptance criteria

- [ ] if current time is after “effective” but before “ends”, “[onset] [time zone] -” is replaced with “until” in banner
- [ ] if current time is after “effective” but before “ends”, “[onset] [time zone] -” is replaced with “until” in hazard details
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by colinmurphy01** [comment]
@kmranjo can you confirm the bug and the solution

**Comment by kmranjo** [comment]
I'm not sure I'm following. I know we added some logic to make sure that if the effective or ends time is not available, the components both display something that looks right. But it seems like in this example both variables are available, but we're asking to insert logic that removes the effective time because current time is later than that? 
Unless I'm forgetting a convo we had about this at some point, that approach doesn't sound familiar, and would be a shift away from the information as it gets displayed now on the site.

**Comment by kmranjo** [comment]
Discussed and tweaked the language in the ticket. Sorry for my confusion!

**Comment by colinmurphy01** [comment]
@kmranjo how should we handle this issue? Do we want the hazard details to have the full timespan included or shorten it if it's active?

**Comment by kmranjo** [comment]
@colinmurphy01 I think we originally had the full timespan, but then decided to shorten it? Given the change we are making to the alert list though, I think we can shift our approach. With the shortened copy in the Alert List, I think it makes more sense to keep the full timespan in the Alert Details, unless anyone can think of a reason not to.

**Comment by colinmurphy01** [comment]
That's what I was thinking as well. I'll close this and we can monitor in testing
