### ISSUE TITLE
Spike: Workbench - Admin

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#752]
Coming out of previous spikes we've identifed Workbench as promising Drupal module that can support our admin needs (and potentially CMS needs as well).

Let's test if it can support our initial roles/permissions design
- Anyone with a NOAA email can create an default account, as read-only
- Account can be assigned as a super admin
- Super Admin can create/assign WFO admin role with correct permissions
- WFO admin can create/assign WFO Contributor with correct permissions
- Super Admin can create/assign National admin role with correct permissions
- National admin can create/assign National Contributor role with correct permissions

@loganmcdonald-noaa will install it in her sandbox and then setup Katrina's account with Super Admin permissions

Goal: We need to assess if an out of the box tool can satisy our unique needs or if we'll need to build a custom module.

After this we can then document if workbench is sufficient and pursue #650 and #523

**Comment by loganmcdonald-noaa** [comment]
This has been setup in https://weathergov-eric.app.cloud.gov/

**Comment by kmranjo** [comment]
Did a bunch of testing in the environment @loganmcdonald-noaa set up, and here's what I have so far. 

Things I could do: 
- Sort dynamic content into editorial sections
- Organize those sections into a hierarchy  
- Create roles with differing levels of permissions and assign users to them (not clear if this is part of WB or just Drupal) 
- Assign users to specific editorial sections so that the permissions of their assigned role apply **_only_** to the content in that section
- Confirm that users in the above scenario couldn't access anything they shouldn't be able to

Things I could only sort of do: 
- Allow authenticated users (those logged in but not yet assigned a role) to view content even if they cannot modify it. I think this is likely not a WB thing, but more me not understanding some of the settings under role permissions. 
- Sort static content into the same editorial sections. WB makes it look like this should be possible, so my guess is that it's just an artifact of the limited taxonomy we've built so far (meaning we're only working with WFOs and you can't currently add that term to a page)  
- Assign users to a parent section and have them automatically granted access to all children of that parent. I actually **was** able to do this for a direct parent/child relationship, but when I tried to do it for a grandparent/parent/child it didn't work the same and I'm not sure why.

Things I could not do:  
Apply the same hierarchy to both content and users, allowing area admins to manage both content and users within their purview. I think from what I've read that WB isn't designed to do this, so it may just not be expected. We would maybe need to lean on a different tool for this piece.

**Comment by kmranjo** [comment]
Met with Logan today and we talked through a few things. Confirmed that the items I listed above in the "can only sort of do" were all things that just came down to how I had configured them. When configured correctly, they work as intended.

**Comment by colinmurphy01** [comment]
That is fantastic news

**Comment by colinmurphy01** [comment]
Let's discuss next steps tomorrow in Des/Eng review.

**Comment by loganmcdonald-noaa** [comment]
With the des/eng review and discussion with @coreypieper today, we can close out this spike and move to #781 next sprint.
