### ISSUE TITLE
Create links for URLs that are shown in hazard text

### ISSUE THREAD

**Issue by shadkeene** [weather-gov/weather.gov#757]
It would be helpful for any URL that is shared in a hazard to be clickable.  This apparently involves some significant coding to parse out/identify URLs.  
![image](https://github.com/weather-gov/weather.gov/assets/139174561/c1b42dcf-77e1-49d3-b174-fe3ee4b84d23)

**Comment by greg-does-weather** [comment]
Do those links always go somewhere on `weather.gov`? Do they always start with `https://`? If so, then parsing them into links shouldn't be too bad. The only wonky cases I can think of would be when the URL is immediately followed by a punctuation mark, but I imagine that's not too hard to solve for. The trick is remembering to do it. 😄 

### Longer, more general response to parsing URLs from text

It's complicated, but considering that NWS has full control over the text, we can probably hand-wave a lot of the complexities. Like if we agree to a set of rules for what we will detect as a URL, then it gets easier. E.g.:

1. It must start with `https://`. This is a huge simplification because it makes it easier for us to identify when a URL might be starting.
   - We could make an exception for things that start with `weather.gov` (and/or `noaa.gov`, etc.), but we should require that the target of the link be HTTPS.
3. It must not contain username and password fields (ie, `https://user:pass@weather.gov/` would be invalid)
4. It must only contain spec-compliant characters
   - Technically speaking, there are only 84 valid characters in a spec-compliant URL. Any other Unicode characters may be used by "URL-encoding" them into a set of those 84 valid characters. (For example, a space character is not valid, so it gets encoded as `%20`.) In practice, the encoding of URLs is done by low-level system libraries, not humans who write things, so our authors would probably use un-encoded characters. We would not be able to detect that `https://weather.gov/nashville wfo` was a single URL without it being encoded to `https://weather.gov/nashville%20wfo`.
   - Not all valid characters are valid in all positions of a URL, either.
   - For future reference, the spec-compliant characters are:
   ```
   ABCDEFGHIJKLMNOPQRSTUVWXYZ
   abcdefghijklmnopqrstuvwxyz
   0123456789
   - . _ ~ : / ? # [ ] @ ! $
   & ' ( ) * + , ; =
   ```
5. No ports. So no URLs like `https://secret-server.weather.gov:3300/` – that `:3300` part at the end is the port to use. This is really for security reasons, because the parsing would be pretty straightforward.

**Comment by coreypieper** [comment]
Here's another URL example. 
![Screenshot 2024-04-19 at 11 57 26 AM](https://github.com/weather-gov/weather.gov/assets/4570239/3230fca8-a7fd-4869-805a-7fc7450901f4)
