### ISSUE TITLE
Observations: improve how we handle null

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#763]
### Description

Right now when we recieve `null` data for observations within temp and wind we show

- 32º for temp
- 0mph for wind

Update this to reflect null that's consistent with the rest of the experience. Options to consider:
- dashes
- hide it
- leave blank

### Acceptance criteria
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by greg-does-weather** [comment]
Before we can pick this up, we need to know what to replace `null` with. It's totally fine if it's different per measurement and even per place it's displayed.

**Comment by colinmurphy01** [comment]
@igorkorenfeld @kmranjo any ideas?

My suggestions above were
- dashes
- hide it
- leave blank

**Comment by kmranjo** [comment]
I would lean toward dashes. Hiding it makes for an inconsistency that users may not understand, and leaving it blank will look a bit strange. I think dashes are a little more easily recognizable as something to reflect "hey we don't have the data for this"

**Comment by greg-does-weather** [comment]
That makes a lot of sense to me. Do you know if that would also make sense in a screenreader context? I can also ask the accessibility guild for thoughts.

**Comment by greg-does-weather** [comment]
Actually, since we render that narrative text separately, I think it'd make sense to just say plainly that the temperature, wind, whatever is unavailable. I agree that in the visual world, the dashes are pretty recognizable, but I'm just thinking about hearing "dash dash degrees" and that doesn't make any sense to me.

**Comment by colinmurphy01** [comment]
@greg-does-weather agree

**Comment by igorkorenfeld** [comment]
My instinct is to put "not available" or "N/A"

**Comment by colinmurphy01** [comment]
@igorkorenfeld I think you / design should make the call on this. I kinda don't want to overcomplicate it or let it fester. 

CC @shadkeene @coreypieper

**Comment by partly-igor** [comment]
"N/A" seems to fit the space well and I _think_ is common enough that it will be clear

**Comment by greg-does-weather** [comment]
It turns out, we currently won't ever encounter the null temperature because we use that as our indication to move on to another observation station. If we get through 3 observation stations with null temperature, we don't return current conditions at all.

I think #569 will speak to that eventually, but I guess we should decide how we want to proceed in the meantime. I think my proposal is to fix null on wind speed and put a comment in #569 about how we'll handle null temperatures once that's no longer the (sole?) determinant of an invalid observation.

**Comment by colinmurphy01** [comment]
That seems like a good path forward.

@coreypieper or @shadkeene feel free to object.
