### ISSUE TITLE
Implement Workbench

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#781]
- [x] Install workbench
- [x] Configure it to use our taxonomy
- [ ] Update taxonomy to include hierarchy/subcategories

**Comment by loganmcdonald-noaa** [comment]
I've merged the basic install but there are a couple things I want to update before this is done including the new taxonomy structure.

**Comment by loganmcdonald-noaa** [comment]
Am trying to update the taxonomies according to https://www.weather.gov/organization_prv and running into some issues with it. Some WFOs are under multiple states (New Jersey and Pennsylvania both have PHI for example). Also some of the WFOs seem to be missing… Twin Cities for example isn’t present here. I might consider this ticket Done since Workbench/Access is implemented and return to data normalization once we figure out a complete source for how WFOs should be organized under states/regions.
