### ISSUE TITLE
Wrong city names displayed for cities in U.S. Territories 

### ISSUE THREAD

**Issue by partly-igor** [weather-gov/weather.gov#957]
### Description
Searching for and picking a number of cities in  U.S. territories returns point location pages with seemingly correct grid points and data, but the wrong city name. 
Examples: 
"Guam Intl Airport, Guam, GUM" returns a point location page with "[Eastport, ME](http://localhost:8080/point/13.484/144.797)" as the city name, 13.484/144.797 as the grid point
"San Juan, PRI" -> [North Key Largo, FL](http://localhost:8080/point/18.465/-66.117) : 18.465,-66.117
"Cruz Bay, St. John, VRI" -> [North Key Largo, FL](http://localhost:8080/point/18.332/-64.794) : 18.332, -64.794, 

### Acceptance criteria
- [ ] Searching for location that are located in U.S. territories returns the correct name
- [ ] Tests have been implemented or modified to capture the bug
- [ ] Changes have been tested for accessibility

**Comment by eric-gade** [comment]
## Discoveries so far ##
At first, I thought this was a simple matter of us filtering out anything that was not the `US` country code from the geonames data, when in fact the US territory locations use their own country codes in the source dataset. This is still true, but it's not the whole story.
  
When ingesting, we expect the county FIPS administrative codes to match what we have in the `weathergov_geo_counties` table. However according to [the data description file](http://download.geonames.org/export/dump/readme.txt), `admin1` and `admin2` codes can have varied meanings/classifications. It appears that for Puerto Rico, some other system is being used in conjunction (see below). For Guam, no FIPS codes are being used _at all_.
  
### Puerto Rico ###
Here is an example of two places parsed from the geonames set, with the field names included:
```json
[{
    "geonameId": "4562778",
    "name": "Barranquitas",
    "asciiName": "Barranquitas",
    "alternateNames": "Barankitas,Barrankitas,ba lan ji ta si,barankuyitasa,Баранкитас,Барранкітас,بارانکیتاس، پورٹو ریکو,বারাংকুয়িতাস,巴蘭基塔斯",
    "lat": "18.18662",
    "lon": "-66.30628",
    "featureClass": "P",
    "featureCode": "PPLA",
    "countryCode": "PR",
    "cc2": "",
    "admin1": "019",
    "admin2": "7268235",
    "admin3": "",
    "admin4": "",
    "population": "3021",
    "elevation": "603",
    "dem": "603",
    "timezone": "America/Puerto_Rico",
    "modified": "2015-08-03"
  },
  {
    "geonameId": "4562812",
    "name": "Bartolo",
    "asciiName": "Bartolo",
    "alternateNames": "",
    "lat": "18.36134",
    "lon": "-65.8385",
    "featureClass": "P",
    "featureCode": "PPL",
    "countryCode": "PR",
    "cc2": "",
    "admin1": "119",
    "admin2": "7268449",
    "admin3": "",
    "admin4": "",
    "population": "1260",
    "elevation": "61",
    "dem": "60",
    "timezone": "America/Puerto_Rico",
    "modified": "2015-08-03"
  }]
```
  
All FIPS entries for PR in our correct counties set will start with `72`. These codes to as well, but they do not match, since our FIPS codes are 5 digits only. However, if you take `72` and then add the three-digit code used in `admin1` in these examples, you get _correct_ FIPS codes for the location (I've tested a few locally in the database and they seem to fit so far).
  
### Guam ###
Guam does not appear to use FIPS codes at all, and, in fact, their `admin1` codes can sometimes match US state codes, which is extra confusing. Here is an example output from geonames:
```json
[{
    "geonameId": "7268049",
    "name": "Mangilao Village",
    "asciiName": "Mangilao Village",
    "alternateNames": "Manguilao,Manguuao",
    "lat": "13.44761",
    "lon": "144.80109",
    "featureClass": "P",
    "featureCode": "PPLA",
    "countryCode": "GU",
    "cc2": "",
    "admin1": "MA",
    "admin2": "",
    "admin3": "",
    "admin4": "",
    "population": "15191",
    "elevation": "62",
    "dem": "58",
    "timezone": "Pacific/Guam",
    "modified": "2013-06-30"
  },
  {
    "geonameId": "7873866",
    "name": "Mongmong-Toto-Maite Village",
    "asciiName": "Mongmong-Toto-Maite Village",
    "alternateNames": "",
    "lat": "13.46857",
    "lon": "144.78214",
    "featureClass": "P",
    "featureCode": "PPLA",
    "countryCode": "GU",
    "cc2": "",
    "admin1": "MT",
    "admin2": "",
    "admin3": "",
    "admin4": "",
    "population": "6825",
    "elevation": "43",
    "dem": "46",
    "timezone": "Pacific/Guam",
    "modified": "2013-07-07"
  }]
```
  
Are these in Mass and Montana? Nope. There are also no FIPS to compare to.
  
### Other interesting files ###
Geonames provides data description files for the [admin1](http://download.geonames.org/export/dump/admin1CodesASCII.txt) and [admin2](https://download.geonames.org/export/dump/admin2Codes.txt) fields. Perhaps we can find some matching clues in there and come up with a way to align all the data.

**Comment by elijah-wright** [comment]
mapping out the data through FIPS is going to be difficult. would it be potentially better to use geonameIds and convert those into FIPS wherever possible? Guam also has postal codes

**Comment by colinmurphy01** [comment]
Was this resolved?
